import Head from "next/head"
import Header from "~/components/templetes/Header"

const Layout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {children}
      </main>
    </div>
  )
}

export default Layout